export type Usage = {
  prompt_tokens:     number
  completion_tokens: number
  reasoning_tokens?:  number
  total_tokens:      number
  completion_tokens_details?:{
    /**
     * When using Predicted Outputs, the number of tokens in the prediction that
     * appeared in the completion.
     */
    accepted_prediction_tokens?: number;

    /**
     * Audio input tokens generated by the model.
     */
    audio_tokens?: number;

    /**
     * Tokens generated by the model for reasoning.
     */
    reasoning_tokens?: number;

    /**
     * When using Predicted Outputs, the number of tokens in the prediction that did
     * not appear in the completion. However, like reasoning tokens, these tokens are
     * still counted in the total completion tokens for purposes of billing, output,
     * and context window limits.
     */
    rejected_prediction_tokens?: number;
  }
  prompt_tokens_details?: {
    accepted_prediction_tokens?: number
    audio_tokens?:    number
    cached_tokens?:   number
    image_tokens?:    number
    readoning_tokens?: number
    rejected_prediction_tokens?: number
    text_tokens?:     number
  }
}
